# https://github.com/marketplace/actions/auto-generate-changelog
name: Generate changelog
on:
    schedule:
      - cron: '0 0 * * *'  # Runs at 00:00 UTC every day.
    workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@v1.2.5
      with:
        REPO_NAME: 'Rebekah-Chuang/VizAble'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        BRANCH: 'main'
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update `CHANGELOG.md`'
        TYPE: 'feat:Feature,fix:Bug Fixes,refactor:Refactor,perf:Performance Improvements'
        REGENERATE_COUNT: -1 # Regenerate n recent releases' changelog.
        UNRELEASED_COMMITS: 'true' # Whether to include unreleased commits in the changelog
