name: "Lint Commit Messages"

on: [push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetches the entire history which is necessary for commitlint to work correctly

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: './commitlint.config.js'
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Set to true if you want warnings to cause the action to fail
          failOnWarnings: 'false'
          # Add this line to check only the latest commit
          firstParent: true