# name: Lint Commit Messages

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   commitlint:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out the repository
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0 # Ensures commit history is pulled

#       - name: Install Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 'lts/*'

#       - name: Install Dependencies
#         run: yarn install

#       - name: Lint Commit Messages
#         run: npx commitlint --from=HEAD~1 --to=HEAD --verbose

name: Lint Commit Messages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0