# reference: https://github.com/JRubics/poetry-publish

# this workflow is triggered when a new release is created(after `python-semantic-release` workflow passed and determined an update is necessary)
# and it will publish the package with an updated version to PyPI using poetry-publish action(`poetry build && poetry publish` if run locally)

name: pypi-publish
on:
  # triggered when a new release is created
  release:
    types: [created]
  # triggered manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}