# reference: https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html

# this workflow automatically checks commit history and determine if a new release should be made
# fix --> patch release, feat --> minor release, breaking --> major release
# if so, it will create a new release, tag it, update the version in `pyproject.toml` & `VizAble/__init__.py`, and update the `CHANGELOG.md`
# a new release will also trigger the `pypi-publish` workflow to publish the new release to PyPI

name: python-semantic-release

on:
  # triggered every three days at 00:00 EST (05:00 UTC)
  schedule:
    - cron: '0 5 */3 * *'

  # triggered manually
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
        