name: shinyappsio-deployment

on:
  # Triggered manually or when there are changes pushed to the master branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Use the appropriate Python version
    
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
    
    # reference: https://testdriven.io/tips/eb1fb0f9-3547-4ca2-b2a8-1c037ba856d8/
    - name: Generate requirements.txt
      run: |
        poetry export --without-hashes --format=requirements.txt > requirements.txt
        echo "-e git+https://github.com/Rebekah-Chuang/VizAble.git@main#egg=VizAble" >> requirements.txt

    - name: Check if requirements.txt exists
      run: ls

    - name: Check requirements.txt content
      run: cat requirements.txt || echo "Failed to read requirements.txt"
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    # - name: Install rsconnect-python
    #   run: pip install rsconnect-python

    # - name: Configure rsconnect
    #   run: |
    #     rsconnect add --account rebekah-chuang --name rebekah-chuang --token ${{ secrets.RSCONNECT_TOKEN }} --secret ${{ secrets.RSCONNECT_SECRET }}

    # - name: Deploy to shinyapps.io 
    #   run: |
    #     cd VizAble
    #     ls
    #     rsconnect deploy shiny . --name rebekah-chuang --title VizAble